export const EN_English = {
  "Nav.Home": "Home",
  "Nav.About": "About",
  "Nav.Projects": "Projects",
  "Nav.Contact": "Contact",
  "Home.Greeting": "Greeting",
  "Home.Greeting.Welcome": "Welcome to my portfolio",
  "Home.Greeting.More": "More about me",
  "Home.Greeting.Resume": "Resume",
  "About.About": "About",
  "About.Content_1": `Hi, I'm Nguyen Lim Thai Ho, a front-end developer passionate about making awesome websites. I love turning designs into functional, enjoyable user experiences. `,
  "About.Content_2": `I pay attention to details and enjoy improving website performance. Beyond coding, I stay updated on the latest web trends through online learning. Excited for new challenges and opportunities to grow!`,
  "About.Skills_1": "My",
  "About.Skills_2": "Skills",
  "About.Skills.Front-end": "Front-end",
  "About.Skills.Back-end": "Back-end",
  "About.Skills.Database": "Database",
  "About.Skills.Tools": "Tools",
  "About.Certificates": "Certificates",
  "About.Github.Contributions": "GitHub Contributions",
  "About.Github.Contributions.Label": "contributions in",
  "Projects.IndustryExp": "Industry Experiences",
  "Projects.Company_1": "eton Corp",
  "Projects.Company_1.Position": "Front-end Developer Intern",
  "Projects.Company_1.Content.1":
    "Worked on the company's app on the Zalo Mini App flatform to assist warehouse employees in submitting requests to address the issues they are currently facing.",
  "Projects.Company_1.Content.2":
    "Developed features like barcode/QR code scanning and attaching multiple documents, images, or multimedia files to help support staff better understand the issue and make inputting more efficient.",
  "Projects.Company_1.Content.3":
    "Helped solve bugs and errors in the front-end of the app.",
  "Projects.Company_1.Content.4":
    "Researched and developed a UIPath unattended bot to automate the process of getting incoming emails or email replies, then processing them and sending them back to the back-end to create a request node or comment on an existing request node.",
  "Projects.Personal": "Personal Projects",
  "Projects.MillierStore": "Millier Store 🏬",
  "Projects.MillierStore.Content":
    "Millier Store is an e-commerce website that sells mobile phones, laptops, and accessories. With inspiration from the official Apple website, I aimed to create a responsive and user-friendly design.",
  "Projects.MillierStoreBE": "Millier Store BE 🌐",
  "Projects.MillierStoreBE.Content": `Millier Store BE is a back-end for Millier Store. Currently hosting on Vietnix using the "Hosting Cheap 2" pack and MongoDB for data storage.`,
  "Projects.MySimpleRadio": "My Simple Radio 🎶",
  "Projects.MySimpleRadio.Content": `MySimpleRadio is a simple music player that streams from Youtube. Whether you are studying, playing games, or just relaxing. MySimpleRadio will deliver the best experience and make sure that you can focus on whatever you are doing.`,
  "Projects.ResumeGenerator": "Resume Generator 📰",
  "Projects.ResumeGenerator.Content":
    "MyResume is a simple resume generator that takes your input information and turns it into a resume. The app allows you to download PDF files as well as print out your generated resume.",
  "Projects.MineInUs": "MineInUs 💰",
  "Projects.MineInUs.Content": `MySimpleRadio is a simple music player that streams from Youtube. Whether you are studying, playing games, or just relaxing. MySimpleRadio will deliver the best experience and make sure that you can focus on whatever you are doing.`,
  "Projects.ClothesEcommerce": "Clothes Ecommerce 👚",
  "Projects.ClothesEcommerce.Content":
    "Ecommerce Project completed in my 3rd year of university.",
  "Projects.MyBlog": "MyBlog 📘",
  "Projects.MyBlog.Content": `MyBlog is a simple blog where I can post my daily life stories and my views on life. There were some problems during the deployment process, so a preview isn't available yet.`,
  "Projects.Preview": "Preview",
  "Contact.Contact": "Contact Info",
  "Contact.Description":
    "Feel free to get in touch with me via any of the platforms below.",
};
